### ISSUE TITLE
component included in SB calculations

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-fish-tools/data_dictionary#11]
I recently read a [definition of spawning biomass](https://www.fishbase.de/glossary/Glossary.php?q=spawning+stock+biomass) that was slightly alarming to me. 

```
The total weight of the fish in a stock that are old enough to spawn;
the biomass of all fish beyond the age or size class in which 50% of the individuals are mature.
```

This is not typical right? I see in [Stock Synthesis](https://github.com/nmfs-stock-synthesis/stock-synthesis/blob/4fc3ea2d705b167412f5a65d59d2d53f2feb0b27/SS_popdyn.tpl#L344) that some measure of maturity-at-age is multiplied by numbers at age making the calculation more precise than just summing the biomass at age for those ages that are at least 50% mature.

@iantaylor-NOAA might have comments?

**Comment by iantaylor-NOAA** [comment]
I think the FishBase definition only makes sense if you have values for age at 50% maturity and no maturity ogive.

Yes, SB in SS3 is either the sum of maturity-at-age * numbers-at-age for stocks with age-based maturity, or maturity-at-length * numbers-at-length for stocks with length-based maturity (where you also have access to the derived maturity-at-age calculated as the sum of maturity-at-length * numbers-at-length within each age).

**Comment by kellijohnson-NOAA** [comment]
Ahh yes that makes sense Ian. Thank you.
