### ISSUE TITLE
Choose Top Ten

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-fish-tools/data_dictionary#16]
Narrow down top20.txt to Top Ten. 

1. Z (Giselle) - ubiquitous use
2. spawning biomass - SB vs. SSB
3. index, CPUE, trend - combining terms, including ecosystem time series
4. catch (Chantel)
5. landings (Chantel)
6. forecast (Bai) - forecast vs. projection
7. sex (Bai) - sex vs. gender, codifying 0-9 versus writing it out as a factor
8. spawners per recruit (Chantel) - often abbreviated as SPR where spawning potential ratio is also abbreviated as SPR ... thanks to Kyle Shertzer for pointing this out
9. weight (Giselle) - standardize the unit of fish weight used to kg
10. logR0 - how to abbreviate because technically it is the natural log and not log-based 10 as implied from the prefix of log

Remaining options:
biomass, unfished, recruits, instantaneous fishing mortality (F), length composition, age composition, cohort, fmsy, msy, plus group

**Comment by chantelwetzel-noaa** [comment]
4. Catch
5. Landings

**Comment by kellijohnson-NOAA** [comment]
@Bai-Li-NOAA do you have any preference for a few terms?

**Comment by Bai-Li-NOAA** [comment]
I can work on forecast and sex if they have not been picked yet. 
6. Forecast
7. sex

**Comment by kellijohnson-NOAA** [comment]
@chantelwetzel-noaa I think you are best positioned to handle the battle of SPR. Is this something you are willing to do?

**Comment by GiselleSchmitz-NOAA** [comment]
@kellijohnson-NOAA @Bai-Li-NOAA  do you know which terms remain open?

**Comment by kellijohnson-NOAA** [comment]
@GiselleSchmitz-NOAA I added names to the term list at the top of the issue.

**Comment by GiselleSchmitz-NOAA** [comment]
@kellijohnson-NOAA missed that- thanks! I can work on weight and Z if that seems reasonable.
